replicaCount: 2
image:
  repository: lscr.io/linuxserver/radarr
  tag: latest

service:
  type: ClusterIP
  port: 7878

ingress:
  enabled: true
  className: "nginx" 
  host: "radarr.practica.local"

database:
  enabled: true
  name: radarr
  user: radarr
  password: "" # Se gestionará con un Secret
  storage: 5Gi

persistence:
  config:
    enabled: true
    storage: 10Gi
  downloads:
    enabled: true
    storage: 50Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
