replicaCount: 2

image:
  repository: linuxserver/radarr
  tag: latest
  pullPolicy: IfNotPresent


database:
  user: "radarr"
  storage: "5Gi"
  password: ""  


persistence:
  config:
    storage: "10Gi"
  downloads:
    storage: "50Gi"


autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70


ingress:
  enabled: true
  host: "radarr.practica.local"
  className: "nginx"


service:
  type: ClusterIP
  port: 7878