apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
  labels:
    {{- include "radarr-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.config.storage }}
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-pvc
  labels:
    {{- include "radarr-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.downloads.storage }}
  storageClassName: standard